edgar:
  base_url: "https://www.sec.gov/Archives/edgar"
  user_agent: "SEC Form 4 Research System jakemilken@gmail.com"
  rate_limit:
    max_requests: 8
    time_window: 1

database:
  host: "YOUR_VM_PUBLIC_IP"  # Replace with VM's public IP
  port: 5432
  name: "insider_trading"
  user: "insider_user"
  password: "insider_password"

processing:
  batch_size: 1000
  num_workers: 8
  retry_attempts: 3
  
collection:
  start_year: 1995
  end_year: 2024
  
paths:
  raw_data: "./data/raw"
  processed_data: "./data/processed"
  cache: "./data/cache"

stock_data:
  # yfinance settings
  max_workers: 5
  batch_size: 50
  retry_attempts: 3
  
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Remote access settings
remote:
  connection_timeout: 30
  query_timeout: 300
  retry_attempts: 3
  ssh_tunnel: false  # Set to true if using SSH tunnel 