edgar:
  base_url: "https://www.sec.gov/Archives/edgar"
  user_agent: "SEC Form 4 Research System jakemilken@gmail.com"
  rate_limit:
    max_requests: 8
    time_window: 1

database:
  host: "localhost"  # Local on VM
  port: 5432
  name: "insider_trading"
  user: "insider_user"
  password: "insider_password"

processing:
  batch_size: 1000
  num_workers: 6  # 6 threads for VM scraping
  retry_attempts: 3
  
collection:
  start_year: 1995
  end_year: 2024
  
paths:
  raw_data: "./data/raw"
  processed_data: "./data/processed"
  cache: "./data/cache"

stock_data:
  # yfinance settings
  max_workers: 5
  batch_size: 50
  retry_attempts: 3
  
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# VM-specific settings
vm:
  continuous_mode: true
  restart_on_failure: true
  max_daily_hours: 20  # Run 20 hours per day
  pause_between_years: 300  # 5 minutes between years
  error_threshold: 100  # Stop if 100+ consecutive errors 